-- ============================================================
-- PERSUAXION V1 — DATABASE SCHEMA
-- Run once against your Postgres database.
-- ============================================================

-- Enable uuid generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- SHOPS
-- One row per connected Shopify store.
-- ============================================================
CREATE TABLE IF NOT EXISTS shops (
  shop_domain   TEXT PRIMARY KEY,
  installed_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_active     BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================================
-- SESSIONS
-- One row per browser session (anonymous or identified).
-- session_id is generated by the SDK (UUID v4).
-- ============================================================
CREATE TABLE IF NOT EXISTS sessions (
  session_id              UUID PRIMARY KEY,
  anonymous_user_id       UUID NOT NULL,
  shop_domain             TEXT NOT NULL REFERENCES shops(shop_domain),
  shopify_customer_id     TEXT,                  -- NULL if guest
  is_new_user             BOOLEAN NOT NULL,
  page_type               TEXT,                  -- 'product', 'collection', etc.
  product_id              TEXT,
  variant_id              TEXT,
  started_at              TIMESTAMPTZ NOT NULL,
  last_active_at          TIMESTAMPTZ NOT NULL
);

-- ============================================================
-- RAW_EVENTS
-- Every raw DOM event received from the JS SDK.
-- Source of truth. Never mutated after insert.
-- ============================================================
CREATE TABLE IF NOT EXISTS raw_events (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id        UUID NOT NULL REFERENCES sessions(session_id),
  anonymous_user_id UUID NOT NULL,
  shop_domain       TEXT NOT NULL,
  event_type        TEXT NOT NULL,  -- 'click' | 'scroll' | 'modal_open' | etc.
  timestamp         TIMESTAMPTZ NOT NULL,
  page_url          TEXT,
  page_type         TEXT,
  product_id        TEXT,
  element_text      TEXT,
  element_type      TEXT,
  metadata          JSONB,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- NORMALIZED_SIGNALS
-- Output of the signal abstraction layer.
-- One raw_event can produce zero or more signals.
-- Never mutated after insert.
-- ============================================================
CREATE TABLE IF NOT EXISTS normalized_signals (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id       UUID NOT NULL REFERENCES sessions(session_id),
  raw_event_id     UUID NOT NULL REFERENCES raw_events(id),
  signal_type      TEXT NOT NULL,  -- e.g. 'SIZE_CONTENT_INTERACTION'
  intent_category  TEXT NOT NULL,  -- 'fit_usage' (extensible later)
  score_value      INT NOT NULL,   -- score contribution of this signal
  is_explicit      BOOLEAN NOT NULL DEFAULT FALSE,  -- true for chat keyword matches
  detected_at      TIMESTAMPTZ NOT NULL,
  metadata         JSONB           -- matched_keyword, element_text, etc.
);

-- ============================================================
-- INTENT_STATES
-- Current intent state per session. Upserted on every update.
-- One row per session. Reflects the live state.
-- ============================================================
CREATE TABLE IF NOT EXISTS intent_states (
  session_id         UUID PRIMARY KEY REFERENCES sessions(session_id),
  intent             TEXT NOT NULL DEFAULT 'fit_usage',
  score              INT NOT NULL DEFAULT 0,
  confidence         TEXT NOT NULL DEFAULT 'none', -- none|medium|strong|very_strong
  explicit_detected  BOOLEAN NOT NULL DEFAULT FALSE,
  first_detected_at  TIMESTAMPTZ,       -- set when confidence first leaves 'none'
  last_updated_at    TIMESTAMPTZ NOT NULL,
  top_signals        JSONB              -- ordered array of top signal type strings
);

-- ============================================================
-- INTENT_TRANSITIONS
-- Immutable audit log of every upward confidence change.
-- Append-only. Never updated or deleted.
-- ============================================================
CREATE TABLE IF NOT EXISTS intent_transitions (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id          UUID NOT NULL REFERENCES sessions(session_id),
  intent              TEXT NOT NULL,
  from_confidence     TEXT NOT NULL,
  to_confidence       TEXT NOT NULL,
  score_at_transition INT NOT NULL,
  triggering_signal   TEXT NOT NULL,
  transitioned_at     TIMESTAMPTZ NOT NULL
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_sessions_shop
  ON sessions(shop_domain);

CREATE INDEX IF NOT EXISTS idx_raw_events_session
  ON raw_events(session_id);

CREATE INDEX IF NOT EXISTS idx_raw_events_shop
  ON raw_events(shop_domain);

-- This index is the hot path: rolling window score calculation
CREATE INDEX IF NOT EXISTS idx_signals_session_time
  ON normalized_signals(session_id, detected_at DESC);

CREATE INDEX IF NOT EXISTS idx_intent_states_confidence
  ON intent_states(confidence);

CREATE INDEX IF NOT EXISTS idx_intent_states_updated
  ON intent_states(last_updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_transitions_session
  ON intent_transitions(session_id);
